const data = {
  products: [
    {
      name: 'Comfort Sneaks',
      category: 'Sneakers',
      image: '/images/sneakers1.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cool and comfortable',
    },
    {
      name: 'Nice Fall',
      category: 'Sneakers',
      image: '/images/sneakers2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Classy and bold',
    },
    {
      name: 'Airforce Sneaks',
      category: 'Sneakers',
      image: '/images/sneakers3.jpg',
      price: 75,
      branch: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'They are popular sneakers',
    },
    
    {
      name: 'Business Outfit',
      category: 'Collection',
      image: '/images/combo1.jpg',
      price: 90,
      branch: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Dress for business',
    },
    {
      name: 'Fall Outfit',
      category: 'Collection',
      image: '/images/combo2.jpg',
      price: 95,
      branch: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A casual combo',
    },
    {
      name: 'Business Casuals',
      category: 'Collection',
      image: '/images/combo3.jpg',
      price: 75,
      branch: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Look great.',
    },
    {
      name: 'Executive',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nibble Made',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Occasion Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Nibble Made',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Charles T',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    }, 
  ]
}

export default data;